replicaCount: 1

image:
  repository: sagarnewdocker/respondnow
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  name: respondnow
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations: { }
  hosts:
    - host: respondnow.io
      paths:
        - /

resources: { }

nodeSelector: { }

tolerations: [ ]

affinity: { }
