apiVersion: v1
kind: Service
metadata:
  name: { { .Release.Name } }-respondnow
spec:
  type: { { .Values.service.type } }
  selector:
    app: { { .Release.Name } }
  ports:
    - port: 8080
      targetPort: 8080
