name: Check Broken Links
on:
  schedule:
    - cron: "0 0 * * 1"  # Runs weekly
  push:
    branches:
      - main

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: "**/*.md"
