name: Gitleaks Scan

on:
  pull_request:
    branches:
      - main
      - main-java
  push:
    branches:
      - main
      - main-java

jobs:
  gitleaks:
    name: Run Gitleaks
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Gitleaks Action
        uses: gitleaks/gitleaks-action@v2
        with:
          fail: true  # Fails workflow if secrets are detected
