name: Build and Publish Docker Image - Server

on:
  push:
    branches:
      - main-java
      - release/*
      - develop
  release:
    types:
      - created

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: respondnow-server

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            IMAGE_TAG=${{ github.event.release.tag_name }}
          else
            # Extract the branch name from GITHUB_REF and handle fallback for tags
            BRANCH_NAME=${GITHUB_REF#refs/heads/}
            if [ "$BRANCH_NAME" == "$GITHUB_REF" ]; then
              BRANCH_NAME=${GITHUB_REF#refs/tags/}
            fi
            IMAGE_TAG=${BRANCH_NAME:-latest}
          fi
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.5" # Adjust the Go version as necessary

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Push Docker image to GitHub Container Registry
        if: |
          github.ref == 'refs/heads/main-java' ||
          startsWith(github.ref, 'refs/heads/release/') ||
          github.ref == 'refs/heads/develop' ||
          github.event_name == 'release'
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            --push . -f server/src/main/docker/Dockerfile

      - name: Post success message
        if: |
          github.ref == 'refs/heads/main' ||
          startsWith(github.ref, 'refs/heads/release/') ||
          github.ref == 'refs/heads/develop' ||
          github.event_name == 'release'
        run: echo "Docker image ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} successfully built and pushed to GitHub Container Registry"
